name:  Oneblock
main:  Oneblock.Oneblock
version:  0.9.2R
api-version: 1.13
author:  MrMarL
softdepend: [PlaceholderAPI]
commands:
  oneblock:
    description: Oneblock main command.
    aliases: ob
    usage: /ob join
  ob j:
  ob ver:
    description: Version.
permissions:
    Oneblock.set:
        description: For admin
        default: op
    Oneblock.join:
        description: For all
        default: true
    Oneblock.invite:
        default: true