name:  Oneblock
main:  Oneblock.Oneblock
version:  1.4.2c
api-version: 1.13
author:  MrMarL
loadbefore: ['Multiverse-Core']
softdepend: ['PlaceholderAPI', 'WorldGuard', 'ItemsAdder', 'Oraxen', 'Nexo', 'CraftEngine']
commands:
  oneblock:
    description: Oneblock main command.
    aliases: ob
    usage: /ob join
  ob j:
permissions:
    Oneblock.set:
        description: For admin
        default: op
    Oneblock.join:
        description: For all
        default: true
    Oneblock.invite:
        default: true
    Oneblock.visit:
        default: false
    Oneblock.ignoreBarrier:
        default: op