name:  Oneblock
main:  Oneblock.Oneblock
version:  1.2.9n
api-version: 1.13
author:  MrMarL
softdepend: [Multiverse-Core , PlaceholderAPI , WorldGuard , ItemsAdder , Oraxen , Nexo]
commands:
  oneblock:
    description: Oneblock main command.
    aliases: ob
    usage: /ob join
  ob j:
  ob ver:
    description: Version.
permissions:
    Oneblock.set:
        description: For admin
        default: op
    Oneblock.join:
        description: For all
        default: true
    Oneblock.invite:
        default: true
    Oneblock.visit:
        default: false
    Oneblock.ignoreBarrier:
        default: op